//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REW_TATTOO_KORAT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.OderMasters = new HashSet<OderMaster>();
        }

        public string UserName { get; set; }
        [DisplayName("ชื่อ")]
        public string FirstName { get; set; }
        [DisplayName("นามสกุล")]
        public string LastName { get; set; }
        [DisplayName("ที่อยู่")]
        public string Address { get; set; }
        [DisplayName("เบอร์โทรศัพท์")]
        public string Tel { get; set; }
        public string EMail { get; set; }
        [DisplayName("รหัสผ่าน")]
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OderMaster> OderMasters { get; set; }
    }
}
