//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REW_TATTOO_KORAT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class OderMaster
    {
        [DisplayName("รหัสการจอง")]
        public int O_ID { get; set; }
        [DisplayName("วันที่จอง")]
        public Nullable<System.DateTime> O_Date { get; set; }
        public string UserName { get; set; }
        [DisplayName("วันที่ใช้งาน")]
        public Nullable<System.DateTime> Do_Date { get; set; }
        [DisplayName("ประเภทลายสัก")]
        public Nullable<int> Tattoo_ID { get; set; }
        [DisplayName("ราคา")]
        public Nullable<decimal> Price { get; set; }
        [DisplayName("รายละเอียด")]
        public string Description { get; set; }
        [DisplayName("สถานะ")]
        public string Status { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Tattoo Tattoo { get; set; }
    }
}
