//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REW_TATTOO_KORAT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class REW_TATTOO_DBEntities : DbContext
    {
        public REW_TATTOO_DBEntities()
            : base("name=REW_TATTOO_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<OderMaster> OderMasters { get; set; }
        public virtual DbSet<Tattoo> Tattoos { get; set; }
        public virtual DbSet<Tattoo_Type> Tattoo_Type { get; set; }
    }
}
