//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REW_TATTOO_KORAT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Tattoo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tattoo()
        {
            this.OderMasters = new HashSet<OderMaster>();
        }

        [DisplayName("รหัสลายสัก")]
        public int Tattoo_ID { get; set; }
        [DisplayName("ชื่อลายสัก")]
        public string Tattoo_Name { get; set; }
        [DisplayName("รูป")]
        public string Tattoo_Pic { get; set; }
        [DisplayName("ขนาด")]
        public string Size { get; set; }
        [DisplayName("ราคา")]
        public Nullable<decimal> Unit_Price { get; set; }
        [DisplayName("ประเภท")]
        public Nullable<int> Type_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OderMaster> OderMasters { get; set; }
        public virtual Tattoo_Type Tattoo_Type { get; set; }
    }
}
