//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REW_TATTOO_KORAT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Tattoo_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tattoo_Type()
        {
            this.Tattoos = new HashSet<Tattoo>();
        }

        [DisplayName("รหัสประเภท")]
        public int Type_ID { get; set; }
        [DisplayName("ชื่อประเภท")]
        public string Type_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tattoo> Tattoos { get; set; }
    }
}
